[package]
name = "script-mc-launcher"
version = "0.17.5"
description = "Custom modern Minecraft launcher with instance isolation and mod loader support"
authors = ["Sreeraj SK"]
edition = "2024"
rust-version = "1.90"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.0" }
tauri-plugin-log = "2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
sha1 = "0.10"
sha2 = "0.10"
zip = { version = "2.2", default-features = false, features = ["deflate"] }
flate2 = "1.0"
fastnbt = "2.5"
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
sysinfo = "0.32"
open = "5.3"
base64 = "0.22"
