export const IPC_CHANNELS = {
  CONTENT_PLAN_MODS: 'content:plan-mods',
  CONTENT_LIST_BACKUPS: 'content:list-backups',
  CONTENT_BACKUP_SAVES: 'content:backup-saves',
  CONTENT_RESTORE_BACKUP: 'content:restore-backup',
  CONTENT_GET_RECOVERY_SETTINGS: 'content:get-recovery-settings',
  CONTENT_SAVE_RECOVERY_SETTINGS: 'content:save-recovery-settings',
  CONTENT_LIST_SHADERS: 'content:list-shaders',
  CONTENT_INSTALL_SHADER: 'content:install-shader',
  CONTENT_IMPORT_SHADERS: 'content:import-shaders',
  CONTENT_DELETE_SHADER: 'content:delete-shader',
  CONTENT_SHADER_ENVIRONMENT: 'content:shader-environment',
  CONTENT_OPEN_SHADER_FOLDER: 'content:open-shader-folder',
  CONTENT_CANCEL_TRANSFER: 'content:cancel-transfer',
  CONTENT_TRANSFER_PROGRESS: 'content:transfer-progress',

  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_IS_MAXIMIZED: 'window:is-maximized',
  WINDOW_CLOSE: 'window:close',

  INSTANCES_LIST: 'instances:list',
  INSTANCES_GET: 'instances:get',
  INSTANCES_CREATE: 'instances:create',
  INSTANCES_UPDATE: 'instances:update',
  INSTANCES_DELETE: 'instances:delete',
  INSTANCES_OPEN_FOLDER: 'instances:open-folder',
  INSTANCES_SET_GROUP: 'instances:set-group',
  INSTANCES_RENAME_GROUP: 'instances:rename-group',
  INSTANCES_DISBAND_GROUP: 'instances:disband-group',
  INSTANCES_DELETE_GROUP: 'instances:delete-group',
  INSTANCES_SAVE_CUSTOM_ICON: 'instances:save-custom-icon',
  INSTANCES_TOGGLE_FAVORITE: 'instances:toggle-favorite',
  INSTANCES_REPAIR: 'instances:repair',
  INSTANCES_BACKUP_SAVES: 'instances:backup-saves',
  INSTANCES_CLONE: 'instances:clone',

  AUTH_GET_STATE: 'auth:get-state',
  AUTH_LOGIN_MICROSOFT: 'auth:login-microsoft',
  AUTH_LOGIN_OFFLINE: 'auth:login-offline',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_SWITCH_ACCOUNT: 'auth:switch-account',

  LAUNCH_START: 'launch:start',
  LAUNCH_STOP: 'launch:stop',
  LAUNCH_STATUS_EVENT: 'launch:status',
  LAUNCH_LOG_EVENT: 'launch:log',

  META_GET_VERSIONS: 'meta:get-versions',
  META_GET_LOADER_VERSIONS: 'meta:get-loader-versions',

  SYSTEM_GET_ENVIRONMENT: 'system:get-environment',
  SYSTEM_OPEN_EXTERNAL: 'system:open-external',
  SYSTEM_OPEN_DIRECTORY: 'system:open-directory',
  SYSTEM_SELECT_FILE: 'system:select-file',

  MODS_SEARCH: 'mods:search',
  MODS_GET_DETAIL: 'mods:get-detail',
  MODS_GET_VERSIONS: 'mods:get-versions',
  MODS_INSTALL: 'mods:install',
  MODS_LIST_INSTALLED: 'mods:list-installed',
  MODS_TOGGLE_INSTALLED: 'mods:toggle-installed',
  MODS_DELETE_INSTALLED: 'mods:delete-installed',
  MODS_SET_CURSEFORGE_KEY: 'mods:set-curseforge-key',
  MODS_GET_CURSEFORGE_KEY: 'mods:get-curseforge-key',

  MODPACKS_SELECT_FILE: 'modpacks:select-file',
  MODPACKS_INSPECT: 'modpacks:inspect',
  MODPACKS_IMPORT: 'modpacks:import',
  MODPACKS_INSTALL_REMOTE: 'modpacks:install-remote',
  MODPACKS_PROGRESS_EVENT: 'modpacks:progress',

  RESOURCEPACKS_LIST_INSTALLED: 'resourcepacks:list-installed',
  RESOURCEPACKS_INSTALL: 'resourcepacks:install',
  RESOURCEPACKS_TOGGLE_INSTALLED: 'resourcepacks:toggle-installed',
  RESOURCEPACKS_DELETE_INSTALLED: 'resourcepacks:delete-installed',
  RESOURCEPACKS_INSTALL_DROPPED: 'resourcepacks:install-dropped',
  RESOURCEPACKS_OPEN_FOLDER: 'resourcepacks:open-folder',

  SCREENSHOTS_LIST: 'screenshots:list',
  SCREENSHOTS_DELETE: 'screenshots:delete',
  SCREENSHOTS_OPEN_FOLDER: 'screenshots:open-folder',

  JAVA_GET_RUNTIMES: 'java:get-runtimes',
  JAVA_DOWNLOAD_RUNTIME: 'java:download-runtime',

  LAUNCHERS_SCAN_ALL: 'launchers:scan-all',
  LAUNCHERS_SCAN_DIRECTORY: 'launchers:scan-directory',
  LAUNCHERS_SELECT_DIRECTORY: 'launchers:select-directory',
  LAUNCHERS_CLONE: 'launchers:clone',
  LAUNCHERS_CLONE_PROGRESS_EVENT: 'launchers:clone-progress',

  FONTS_LIST: 'fonts:list',
  FONTS_INSTALL: 'fonts:install',
  FONTS_DELETE: 'fonts:delete',

  MODS_CHECK_UPDATES: 'mods:check-updates',
  MODS_UPDATE_ALL: 'mods:update-all',
  MODS_UPDATE_PROGRESS_EVENT: 'mods:update-progress',
  MODS_INSTALL_DROPPED: 'mods:install-dropped',

  SERVERS_LIST_ALL: 'servers:list-all',
  SERVERS_LIST_INSTANCE: 'servers:list-instance',
  SERVERS_ADD: 'servers:add',
  SERVERS_REMOVE: 'servers:remove',
  SERVERS_PING: 'servers:ping',
  LAUNCH_QUICK_PLAY: 'launch:quick-play',

  SKINS_LIST: 'skins:list',
  SKINS_SAVE: 'skins:save',
  SKINS_DELETE: 'skins:delete',
  SKINS_SEARCH_PLAYER: 'skins:search-player',
  SKINS_APPLY: 'skins:apply',
  SKINS_GET_ACTIVE: 'skins:get-active',
  SKINS_LIST_CAPES: 'skins:list-capes',
  SKINS_APPLY_CAPE: 'skins:apply-cape',
  SKINS_SAVE_CAPE: 'skins:save-cape',
  SKINS_DELETE_CAPE: 'skins:delete-cape',
  SKINS_SEARCH_OPTIFINE_CAPE: 'skins:search-optifine-cape',


  SETTINGS_GET_GAME: 'settings:get-game',
  SETTINGS_SAVE_GAME: 'settings:save-game',
  SETTINGS_OPEN_FILE: 'settings:open-file',

  UPDATER_CHECK: 'updater:check',
  UPDATER_QUIT_AND_INSTALL: 'updater:quit-and-install',
  UPDATER_STATUS_EVENT: 'updater:status',
  UPDATER_PROGRESS_EVENT: 'updater:progress',
  UPDATER_DOWNLOADED_EVENT: 'updater:downloaded',

  DISCORD_SET_ACTIVITY: 'discord:set-activity',
  DISCORD_CLEAR_ACTIVITY: 'discord:clear-activity'
} as const
